spring:
  mvc:
    hidden-method:
      filter:
        enabled: true
  jersey:
    type: servlet
    servlet:
      load-on-startup: 1
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    url: jdbc:mysql://rsshub.tonal-all.pro:3306/tonal
    username: root
    password: xxxxxxxx
  data:
    redis:
      host: rsshub.tonal-all.pro
      database: 0
      password: xxxxxxx
      jedis:
        pool:
          max-wait: 10ms
          max-active: 10
          min-idle: 2
          max-idle: 8
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
#  web:
#    resources:
#      chain:
#        compressed: true
#        cache: true
#      cache:
#        period: 86400

server:
  port: 8006

  servlet:
    register-default-servlet: true

aliyun:
  domain: oss-cn-beijing.aliyuncs.com
  bucketName: tonall
  accessKeyId: xxxxxxxxxxxxxxxxxxxx
  accessKeySecret: xxxxxxxxxxxxxxxxxx
  dir: /img
